#!/usr/bin/env python3
# Software License Agreement (BSD)
#
# @author    Chris Iverach-Brereton <civerachb@clearpathrobotics.com>
# @copyright (c) 2025, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# * Neither the name of Clearpath Robotics nor the names of its contributors
#   may be used to endorse or promote products derived from this software
#   without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

"""
This file is the main entrypoint for production tests.

This script will run through each of the tests needed for the configured platform
and log the results to a specified output file.

The output file is in markdown format. Markdown files are human-readable, but
you can also install markdown renderers for Chrome, Firefox, VSCode, and other
browsers & editors.
"""

import rclpy
from rclpy.node import Node

from datetime import datetime
import os

from clearpath_config.clearpath_config import ClearpathConfig
from clearpath_config.common.types.platform import Platform
from clearpath_config.common.utils.yaml import read_yaml

from clearpath_tests import (
    drive_test_fixed,
    fan_test,
    light_test,
    rotation_test_fixed,
)


class TestingNode(Node):

    common_tests = [
        drive_test_fixed,
        rotation_test_fixed,
    ]

    tests_for_platform = {
        Platform.A200: [
        ],
        Platform.A300: [
            light_test,
            fan_test,
        ],
        Platform.DD100: [
        ],
        Platform.DD150: [
        ],
        Platform.DO100: [
        ],
        Platform.DO150: [
        ],
        Platform.GENERIC: [
        ],
        Platform.J100: [
        ],
        Platform.R100: [
        ],
        Platform.W200: [
        ]
    }

    def __init__(self, node_name='clearpath_production_test_node'):
        super().__init__(node_name)

        self.report_file = self.get_parameter_or(
            'report_file',
            f'/tmp/clearpath_test_results.{datetime.now().strftime("202501281032")}.md'
        )

        self.setup_path = self.get_parameter_or('setup_path', '/etc/clearpath')
        self.setup_file = os.path.join(self.setup_path, 'robot.yaml')
        self.clearpath_config = ClearpathConfig(read_yaml(self.setup_file))

    def destroy_node(self):
        """
        Clean up any in-progress tests.

        Also make sure the log file is closed.
        """
        return super().destroy_node()

    def print_summary(self):
        print('TODO: report summary')

    def write_header(self):
        """
        Initialize the report file.

        This dumps some initial meta-data and a copy of robot.yaml
        """
        with open(self.report_file, 'w') as report:
            report.write(f"""# Clearpath Test Report

{datetime.now().strftime('%Y-%m-%d %H:%M')}

Report generated by user {os.getlogin()}

Setup path: {self.setup_path}

Platform (serial): {self.clearpath_config.get_platform_model()} ({self.clearpath_config.get_serial_number()})

## robot.yaml
""")
        self.copy_file_contents(self.setup_file, 'yaml')

    def copy_file_contents(self, path, format=None):
        """
        Copy the raw contents of a file into a code block

        @param path  The path of the file to copy
        @param format  Optional code formatting parameter (e.g. python, bash, yaml, xml, ...)
        """
        with open(path, 'r') as setup_file:
            file_contents = setup_file.readlines()
        self.write_code(file_contents, format)

    def write_code(self, code, format=None):
        """
        Add a code block to the report

        The code block will always have a newline added before and after it

        @param code  Either a string or an array of strings representing the lines of code
        @param format  The markdown-compatible language (e.g. python, bash, yaml, xml, ...)
        """

        with open(self.report_file, 'a') as report:
            if format:
                report.write(f'\n```{format}')
            else:
                report.write('\n```')

            if type(code) is str:
                if not code.startswith('\n'):
                    report.write('\n')
                report.write(code)
                if not code.endswith('\n'):
                    report.write('\n')
            else:
                if not code[0].startswith('\n'):
                    report.write('\n')
                for line in code:
                    report.write(line)
                if not code[-1].endswith('n'):
                    report.write('\n')

            report.write('```\n')

    def run_tests(self):
        """
        Go through the tests one at a time, logging the results as we go

        The exact tests executed depends on the configured platform
        """
        self.write_header()

        platfom = self.clearpath_config.get_platform_model()
        for test in self.tests_for_platform[platfom]:
            test.main()

        for test in self.common_tests:
            test.main()



def main(args=None):
    rclpy.init(args=args)
    test_node = TestingNode()

    try:
        test_node.run_tests()
        print(f'Tests complete. See {test_node.report_file} for full results')
        test_node.print_summary()
    except FileNotFoundError as err:
        test_node.get_logger().error(f'Failed to write report: {err}')
    except PermissionError as err:
        test_node.get_logger().error(f'Insufficient permissions to write report: {err}')
    except KeyboardInterrupt:
        test_node.get_logger().info('User aborted')
    rclpy.shutdown()

if __name__ == '__main__':
    main()