#!/usr/bin/env python3

from clearpath_config.clearpath_config import ClearpathConfig
from clearpath_config.common.types.platform import Platform
from clearpath_generator_common.common import BaseGenerator
from clearpath_platform_msgs.msg import RGB, Lights 

from enum import Enum
import os

import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_system_default

class LightTest(Node):

    def __init__(self, setup_path='/etc/clearpath'):
        super().__init__('light_test')
        self.setup_path = setup_path

        # Define paths
        self.config_path = os.path.join(self.setup_path, 'robot.yaml')

        # Parse YAML into config
        self.clearpath_config = ClearpathConfig(self.config_path)
        self.platform = self.clearpath_config.platform.get_platform_model()

        # Params
        self.lights_topic = self.get_parameter_or('lights_topic', 'platform/cmd_lights')
        self.publish_rate = self.get_parameter_or('publish_rate', 2)


        self.publisher = self.create_publisher(Lights, self.lights_topic, qos_profile_system_default)
        self.publish_timer = self.create_timer(1 / self.publish_rate, self.publish_callback)
        self.colour = 0

    def publish_callback(self):
        # Define the message to be sent
        msg = Lights()

        led = RGB()
        if self.colour == 0:
            for _ in range(4):
                led.red = int(0)
                led.blue = int(10)
                led.green = int(0)
                msg.lights.append(led)
            self.colour = 1
        elif self.colour == 1:
            for _ in range(4):
                led.red = int(0)
                led.blue = int(0)
                led.green = int(10)
                msg.lights.append(led)
            self.colour = 2
        elif self.colour == 2:
            for _ in range(4):
                led.red = int(10)
                led.blue = int(0)
                led.green = int(0)
                msg.lights.append(led)
            self.colour = 3
        elif self.colour == 3:
            for _ in range(4):
                led.red = int(5)
                led.blue = int(5)
                led.green = int(5)
                msg.lights.append(led)
            self.colour = 4
        elif self.colour == 4:
            for _ in range(4):
                led.red = int(0)
                led.blue = int(0)
                led.green = int(0)
                msg.lights.append(led)
            self.colour = 0
        # Publish the message
        self.publisher.publish(msg)


def main():
    setup_path = BaseGenerator.get_args()
    rclpy.init()

    lt = LightTest(setup_path)

    rclpy.spin(lt)

    dt.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()